language: node_js
node_js:
  - "4.3"
install:
  - npm install -g elm@0.18.0
  - elm-package install -y
script:
  - elm make Scene.elm --output=dotloverc.js
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
